<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove=".vs\2D-Game\**" />
    <EmbeddedResource Remove=".vs\2D-Game\**" />
    <None Remove=".vs\2D-Game\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="obj\Debug\net9.0-windows\.NETCoreApp,Version=v9.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net9.0-windows\The Fourest Seven.AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include=".config\dotnet-tools.json" />
    <Content Include=".vs\VSWorkspaceState.json" />
    <Content Include="obj\project.assets.json" />
    <Content Include="obj\The Fourest Seven.csproj.nuget.dgspec.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.*" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.*" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include=".vs\The Fourest Seven.slnx\v18\" />
    <Folder Include="bin\Debug\net9.0-windows\" />
    <Folder Include="bin\Release\net9.0-windows\" />
    <Folder Include="obj\Debug\net9.0-windows\refint\" />
    <Folder Include="obj\Debug\net9.0-windows\ref\" />
  </ItemGroup>
  <ItemGroup>
    <None Include=".vs\slnx.sqlite" />
    <None Include=".vs\The Fourest Seven.slnx\FileContentIndex\48a20773-f3d7-40ea-8a98-12bca74346a2.vsidx" />
    <None Include="obj\Debug\net9.0-windows\The Fourest Seven.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net9.0-windows\The Fourest Seven.assets.cache" />
    <None Include="obj\Debug\net9.0-windows\The Fourest Seven.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net9.0-windows\The Fourest Seven.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\project.nuget.cache" />
    <None Include="obj\The Fourest Seven.csproj.nuget.g.props" />
    <None Include="obj\The Fourest Seven.csproj.nuget.g.targets" />
  </ItemGroup>
</Project>